services:
    _defaults:
        autowire: true
        autoconfigure: true 


    App\ConsoleCommand\:
        resource: '../../src/App/ConsoleCommand/*'
        tags: 
            - { name: 'console.command' }
