services:
    _defaults:
        autowire: true
        autoconfigure: true 

    Infra\Repository\:
        resource: '../../src/Infra/Repository'

    Domain\Repository\UserRepositoryInterface: '@Infra\Repository\UserRepository'
    Domain\Repository\AddressRepositoryInterface: '@Infra\Repository\AddressRepository'
    Domain\Repository\OfferRepositoryInterface: '@Infra\Repository\OfferRepository'
    Domain\Repository\TagRepositoryInterface: '@Infra\Repository\TagRepository'

