Domain\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        username:
            - Email: 
                message: Veuillez renseigner un email valide
            - NotBlank: 
                message: Champs requis
        password:
            - Type: string
            - NotBlank: 
                message: Champs requis

Domain\Entity\Offer:
    properties:
        title:
            - NotBlank:
                message: Champs requis
        description:
            - NotBlank:
                message: Champs requis
        quantity:
            - NotBlank:
                message: Champs requis
        price:
            - NotBlank:
                message: Champs requis
            - Type:
                type: float
                message: données invalide

Domain\Entity\Address:
    properties:
        name:
            - NotBlank: 
                message: Champs requis
        street:
            - NotBlank: 
                message: Champs requis
        zipcode:
            - NotBlank:
                message: Champs requis
            - Length:
                min: 5
                max: 5
                exactMessage: Code postal invalide
        city:
            - NotBlank:
                message: Champs requis
        streetNumber:
            - NotBlank:
                message: Champs requis
