Domain\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        username:
            - Email: 
                message: Veuillez renseigner un email valide
            - NotBlank: 
                message: Champs requis
        password:
            - Type: string
            - NotBlank: 
                message: Champs requis

Domain\Entity\Address:
    properties:
        name:
            - NotBlank: 
                message: Champs requis
        street:
            - NotBlank: 
                message: Champs requis
        zipcode:
            - NotBlank:
                message: Champs requis
            - Type: 
                type: integer
                message: Code postal invalide
            - Length:
                min: 5
                max: 5
                exactMessage: Code postal invalide
        city:
            - NotBlank:
                message: Champs requis
        streetNumber:
            - NotBlank:
                message: Champs requis
