index:
    path: /
    controller: UI\Actions\IndexAction

# Security
login:
    path: /login
    controller: UI\Actions\Security\LoginAction

register:
    path: /register
    controller: UI\Actions\Security\RegisterAction

logout:
    path: /logout
    methods: GET

# Dashboard
dashboard:
    path: /dashboard
    controller: UI\Actions\Dashboard\IndexAction

# Account
account_detail:
    path: /account
    controller: UI\Actions\Account\GetAccountAction

account_address_add:
    path: /account/address
    methods: ['GET', 'POST']
    controller: UI\Actions\Account\AddAddressAction

account_address_update:
    path: /account/address/{id}
    methods: ['GET', 'POST']
    controller: UI\Actions\Account\UpdateAddressAction

account_address_delete:
    path: /account/address/delete/{id}
    controller: UI\Actions\Account\DeleteAddressAction

#offer
offer_show:
    path: /offer/{id}
    controller: UI\Actions\Offer\ShowAction

offer_add:
    path: /offer
    controller: UI\Actions\Offer\AddOfferAction

offer_update:
    path: /offer/update/{id}
    controller: UI\Actions\Offer\UpdateOfferAction

offer_cancel:
    path: /offer/cancel/{id}
    controller: UI\Actions\Offer\CancelOfferAction

offer_publish:
    path: /offer/publish/{id}
    controller: UI\Actions\Offer\PublishOfferAction
